### PR TITLE
align structure with other repositories of the WG

### PR DESCRIPTION
**Pull request by pchampin**
* move index.html into `spec/`
* more informations an links in README
* add auto-publish rule
   - for the moment, only generate HTML file using Respec for the Github pages
    - Eventually, this will be used to auto-publish it to TR

### CODE REVIEW

**Comment by gkellogg** [comment]
rdf-new and rdf-primer are also notes which use the same process, and will be published to /TR. It's worth running the action even if the group decides not to publish this as a Note.

**Comment by pchampin** [comment]
* as @gkellogg pointed out, as a note it would eventually be published in TR/, so the autopublish action would still be useful
* also, the autopublish action makes some sanity checks that, if broken, have an impact on the editor's draft published on github.io, so it is worth to have it if only for that
* the moving into a spec/ directory is not strictly required, but makes it easier to navigate across our multiple repos

**Review by pfps — APPROVED** [review]
That makes sense.

**Comment by pfps** [comment]
Are the failing checks important?

**Pull request merged**
